<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run()
    {
        // Book Categories
        $categories = [
            ['name' => 'Fiction',         'description' => 'Novels, short stories, and literary works', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Non-Fiction',      'description' => 'Factual and informational books', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Science',          'description' => 'Scientific and research publications', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Technology',       'description' => 'Computer science, engineering, and IT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'History',          'description' => 'Historical events and biographies', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Mathematics',      'description' => 'Mathematics textbooks and references', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Literature',       'description' => 'Classical and modern literature', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['name' => 'Education',        'description' => 'Teaching and learning resources', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
        ];

        $this->db->table('book_categories')->insertBatch($categories);

        // Sample Books
        $books = [
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'isbn' => '978-0061120084',
                'publisher' => 'Harper Perennial',
                'publication_year' => 1960,
                'category_id' => 1,
                'description' => 'A classic novel of racial injustice and childhood innocence.',
                'total_copies' => 5,
                'available_copies' => 5,
                'shelf_location' => 'A-1-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Noli Me Tangere',
                'author' => 'Jose Rizal',
                'isbn' => '978-9710817177',
                'publisher' => 'Anvil Publishing',
                'publication_year' => 1887,
                'category_id' => 7,
                'description' => 'A foundational novel of Philippine literature.',
                'total_copies' => 8,
                'available_copies' => 8,
                'shelf_location' => 'A-2-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen',
                'isbn' => '978-0262033848',
                'publisher' => 'MIT Press',
                'publication_year' => 2009,
                'category_id' => 4,
                'description' => 'Comprehensive textbook on algorithms and data structures.',
                'total_copies' => 3,
                'available_copies' => 3,
                'shelf_location' => 'B-1-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'isbn' => '978-0553380163',
                'publisher' => 'Bantam Books',
                'publication_year' => 1988,
                'category_id' => 3,
                'description' => 'An exploration of cosmology for the general reader.',
                'total_copies' => 4,
                'available_copies' => 4,
                'shelf_location' => 'B-2-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Art of War',
                'author' => 'Sun Tzu',
                'isbn' => '978-1590302255',
                'publisher' => 'Shambhala',
                'publication_year' => 2005,
                'category_id' => 5,
                'description' => 'Ancient Chinese military strategy text.',
                'total_copies' => 3,
                'available_copies' => 3,
                'shelf_location' => 'C-1-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Calculus: Early Transcendentals',
                'author' => 'James Stewart',
                'isbn' => '978-1285741550',
                'publisher' => 'Cengage Learning',
                'publication_year' => 2015,
                'category_id' => 6,
                'description' => 'A widely used calculus textbook for college students.',
                'total_copies' => 6,
                'available_copies' => 6,
                'shelf_location' => 'C-2-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'isbn' => '978-0132350884',
                'publisher' => 'Prentice Hall',
                'publication_year' => 2008,
                'category_id' => 4,
                'description' => 'A handbook of agile software craftsmanship.',
                'total_copies' => 4,
                'available_copies' => 4,
                'shelf_location' => 'B-1-2',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'El Filibusterismo',
                'author' => 'Jose Rizal',
                'isbn' => '978-9710817184',
                'publisher' => 'Anvil Publishing',
                'publication_year' => 1891,
                'category_id' => 7,
                'description' => 'The sequel to Noli Me Tangere.',
                'total_copies' => 6,
                'available_copies' => 6,
                'shelf_location' => 'A-2-2',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'isbn' => '978-0062316097',
                'publisher' => 'Harper',
                'publication_year' => 2015,
                'category_id' => 2,
                'description' => 'A sweeping history of the human species.',
                'total_copies' => 4,
                'available_copies' => 4,
                'shelf_location' => 'C-1-2',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Teaching in the Digital Age',
                'author' => 'Brian Puerling',
                'isbn' => '978-1605544281',
                'publisher' => 'Redleaf Press',
                'publication_year' => 2012,
                'category_id' => 8,
                'description' => 'Smart use of technology in education.',
                'total_copies' => 3,
                'available_copies' => 3,
                'shelf_location' => 'D-1-1',
                'status' => 'available',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('books')->insertBatch($books);
    }
}
